---
all:
  hosts:
    nexus-01:
      ansible_host: 130.193.50.226
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: admin
    ansible_ssh_private_key_file: '~/.ssh/id_rsa.pub'