---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.111.245
    jenkins-agent-01:
      ansible_host: 51.250.84.50
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: admin
    ansible_ssh_private_key_file: '~/.ssh/id_rsa.pub'