---
- name: Install lighthouse
  hosts: lighthouse
  roles:
    - lighthouse
  tags:
    - lighthouse

- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
  tags:
    - click

- name: Install vector
  hosts: vector
  roles:
    - vector
  tags:
    - vector
